# -*- coding: utf-8 -*-
"""etri_파생변수이미지_v1_0_0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/jacobgreen4477/6894afae7b4a9efbc8a8288da5870c4b/etri_v1_0_0.ipynb

> title : 제 4회 ETRI 휴먼이해 인공지능 논문경진대회 <br>
> author : hjy <br>

In our study, we used smartphones, smartwatches, sleep sensors, and self-recording apps to collect daily life logs and sleep health records of study participants in 2024.The data collection procedures and methods followed a similar approach to those used in previous studies. Here, we pu﻿blicly provide the following 12 data items, which comprise a total of 700 days' worth of lifelog data, strictly for non-commercial and academic research purposes only.
- mACStatus: Indicates whether the smartphone is currently being charged.
- mActivity: Value calculated by the Google Activity Recognition API.
- mAmbience: Ambient sound identification labels and their respective probabilities.
- mBle: Bluetooth devices around individual subject.
- mGps: Multiple GPS coordinates measured within a single minute using the smartphone.
- mLight: Ambient light measured by the smartphone.
- mScreenStatus: Indicates whether the smartphone screen is in use.
- mUsageStats: Indicates which apps were used on the smartphone and for how long.
- mWifi: Wifi devices around individual subject.
- wHr: Heart rate readings recorded by the smartwatch.
- wLight: Ambient light measured by the smartwatch.
- wPedo: Step data recorded by the smartwatch.

For the purpose of training a learning model to predict sleep health, fatigue, and stress, the following six metrics were derived from sleep sensor data and self-reported survey records. Each metric consists of values categorized into either two levels (0, 1) or three levels (0, 1, 2), depending on the specific metric. The detailed classification criteria for each metric's levels will be provided in a separate document.These
metrics assign a value of 0 for sleep records that do not meet the recommended guidelines.For instance, the first questionnaire metric (Q1) is assigned a value of 1 on days when an
individual’s self-reported sleep quality exceeds their average over the experimental period, and 0 when it
falls below that average. Similarly, the second and third metrics (Q2 and Q3) are assigned a value of 0
on days when the participant’s fatigue and stress levels, respectively, exceed their average, and a value of
1 when these levels are below average.

- Q1: Overall sleep quality as perceived by a subject immediately after waking up.
- Q2: Physical fatigue of a subject just before sleep.
- Q3: Stress level experienced by a subject just before sleep.
- S1: Adherence to sleep guidelines for total sleep time (TST).
- S2: Adherence to sleep guidelines for sleep efficiency (SE).
- S3: Adherence to sleep guidelines for sleep onset latency (SOL, or SL).

수면 건강, 피로, 스트레스 예측을 위한 학습 모델을 훈련시키기 위해, 수면 센서 데이터와 자기 보고식 설문 기록을 기반으로 다음의 6가지 지표를 도출했습니다.
각 지표는 해당 항목에 따라 두 수준(0, 1) 또는 세 수준(0, 1, 2)으로 구분된 값을 가집니다.
각 지표의 세부 분류 기준은 별도의 문서에서 제공될 예정입니다.

- Q1: 기상 직후 본인이 인지한 전반적인 수면의 질
 - 0: 개인 평균 이하
 - 1: 개인 평균 이상
- Q2: 취침 직전 본인이 느낀 신체적 피로 수준
 - 0: 높은 피로 수준
 - 1: 낮은 피로 수준
- Q3: 취침 직전 본인이 느낀 스트레스 수준
 - 0: 높은 스트레스 수준
 - 1: 낮은 스트레스 수준
- S1: 총 수면 시간(TST) 가이드라인을 준수했는지 3LEVELS
 - 0: 가이드라인 미준수
 - 1: 가이드라인 부분적 준수
 - 2: 가이드라인 완전 준수
- S2: 수면 효율(SE) 가이드라인을 준수했는지 여부
- (SE: 잠자리에 누워 있었던 전체 시간 대비, 실제로 잠든 시간의 비율)
 - 0: 가이드라인 미준수
 - 1: 가이드라인 준수
- S3: 수면 잠들기 지연 시간(SOL 또는 SL) 가이드라인을 준수했는지 여부
- (SOL: 잠자리에 누운 순간부터 실제로 잠드는 데까지 걸린 시간)
 - 0: 가이드라인 미준수
 - 1: 가이드라인 준수

### 📦 라이브러리
"""

! pip install haversine
! pip install optuna
! pip install category_encoders
import pandas as pd
import numpy as np
import os
import sys
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import warnings
from tqdm.auto import tqdm
from collections import Counter
from scipy.stats import entropy
from haversine import haversine  # 설치 필요: pip install haversine

warnings.filterwarnings('ignore')

import re
import ast
from tqdm import tqdm  # ← 추가
from math import radians, cos, sin, asin, sqrt
from datetime import time
from datetime import timedelta
from functools import reduce
from lightgbm import LGBMClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score
import glob
import random
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, roc_curve, f1_score
from sklearn.model_selection import KFold, StratifiedKFold, train_test_split, cross_val_score
import lightgbm as lgb
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from category_encoders import TargetEncoder
from datetime import datetime, timedelta
import warnings
from tqdm.auto import tqdm
from PIL import Image
import matplotlib.pyplot as plt
from tqdm.auto import tqdm

# seed 고정
SD = 42
random.seed(SD)
np.random.seed(SD)
os.environ['PYTHONHASHSEED'] = str(SD)

from google.colab import drive
drive.mount('/content/drive')

# pandas 옵션
pd.set_option('display.max_columns', 999)
pd.set_option('display.max_rows', 999)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.float_format', lambda x: '%0.4f' % x)

def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = True

seed_everything(1)







"""### 📦 데이터 읽기"""

path = '/content/drive/MyDrive/data/ch2025_data_items/'

# 1
mACStatus = pd.read_parquet(path+'ch2025_mACStatus.parquet')
mActivity = pd.read_parquet(path+'ch2025_mActivity.parquet')
mAmbience = pd.read_parquet(path+'ch2025_mAmbience.parquet')
mBle = pd.read_parquet(path+'ch2025_mBle.parquet')
mGps = pd.read_parquet(path+'ch2025_mGps.parquet')
mLight = pd.read_parquet(path+'ch2025_mLight.parquet')
mScreenStatus = pd.read_parquet(path+'ch2025_mScreenStatus.parquet')
mUsageStats = pd.read_parquet(path+'ch2025_mUsageStats.parquet')
mWifi = pd.read_parquet(path+'ch2025_mWifi.parquet')
wHr = pd.read_parquet(path+'ch2025_wHr.parquet')
wLight = pd.read_parquet(path+'ch2025_wLight.parquet')
wPedo = pd.read_parquet(path+'ch2025_wPedo.parquet')

# 2
train = pd.read_csv('/content/drive/MyDrive/data/ch2025_metrics_train.csv')
test = pd.read_csv('/content/drive/MyDrive/data/ch2025_submission_sample.csv')









"""### ✅ mACStatus 핸드폰 충전상태
- Indicates whether the smartphone is currently being charged.
- m_charging : 0/1 상태
- 핸드폰이 오랫 동안 충전했다는 의미?
 - 한 자리에 장시간 머물러 있었다.
 - 핸드폰을 장시간 사용하지 않았다.  
"""

mACStatus['lifelog_date'] = mACStatus['timestamp'].astype(str).str[:10]
mACStatus.head(1)

def process_mACStatus(df):
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df = df.sort_values(['subject_id', 'timestamp'])

    results = []

    for (subj, lifelog_date), group in df.groupby(['subject_id', 'lifelog_date']):
        status = group['m_charging'].values  # 0/1 상태
        times = group['timestamp'].values

        ratio_charging = status.mean()
        sum_charging = status.sum()

        # 상태 전이 횟수
        transitions = (status[1:] != status[:-1]).sum()

        # 연속된 1 상태 길이들
        lengths = []
        current_len = 0
        for val in status:
            if val == 1:
                current_len += 1
            elif current_len > 0:
                lengths.append(current_len)
                current_len = 0
        if current_len > 0:
            lengths.append(current_len)

        avg_charging_duration = np.mean(lengths) if lengths else 0
        max_charging_duration = np.max(lengths) if lengths else 0

        results.append({
            'subject_id': subj,
            'lifelog_date': lifelog_date,
            'charging_ratio': ratio_charging,
            'charging_sum': sum_charging,
            'charging_transitions': transitions,
            'avg_charging_duration': avg_charging_duration,
            'max_charging_duration': max_charging_duration,
        })

    return pd.DataFrame(results)

mACStatus2 = process_mACStatus(mACStatus)

# check
print(f'# mACStatus2 shape: {mACStatus2.shape}')
mACStatus2.head(1)









"""### ✅ mActivity 추정행동
- Value calculated by the Google Activity Recognition API.
 - 0 : IN_VEHICLE
 - 1 : ON_BICYCLE
 - 2 : ON_FOOT
 - 3 : STILL (not moving)
 - 8 : RUNNING
 - 3 : TILTING (This often occurs when a device is picked up from a desk or a user who is sitting stands up.)
 - 4 : UNKNOWN
 - 7 : WALKING

- 근무시간   : 오전 7시부터 오후 6시까지
- 근무외시간 : 오후6시부터 12시까지
"""

mActivity['lifelog_date'] = mActivity['timestamp'].astype(str).str[:10]
mActivity.head(1)

def process_mActivity_by_timezones(df):
    df = df.copy()
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['lifelog_date'] = df['timestamp'].dt.date
    df['hour'] = df['timestamp'].dt.hour

    def summarize(group_df, prefix=''):
        summary = []
        for (subj, date), group in group_df.groupby(['subject_id', 'lifelog_date']):
            counts = group['m_activity'].value_counts(normalize=True)
            counts2 = group['m_activity'].value_counts()
            row = {'subject_id': subj, 'lifelog_date': date}

            for i in range(9):
                row[f'{prefix}activity_{i}_ratio'] = counts.get(i, 0)
                row[f'{prefix}activity_{i}_count'] = counts2.get(i, 0)

            row[f'{prefix}dominant_activity'] = group['m_activity'].mode()[0] if not group['m_activity'].mode().empty else None
            row[f'{prefix}num_unique_activities'] = group['m_activity'].nunique()

            summary.append(row)
        return pd.DataFrame(summary)

    # 전체 데이터 요약 (prefix 없음)
    total_summary = summarize(df)

    # 취침시간 (00:00 ~ 07:00)
    sleeptime_df = df[(df['hour'] >= 0) & (df['hour'] < 7)]
    sleeptime_summary = summarize(sleeptime_df, prefix='sleeptime_')

    # subject_id와 lifelog_date 기준으로 모두 합치기
    result = total_summary.copy()
    result = pd.merge(result, sleeptime_summary, on=['subject_id', 'lifelog_date'], how='left')

    # 컬럼 정렬
    cols = ['subject_id', 'lifelog_date'] + [col for col in result.columns if col not in ['subject_id', 'lifelog_date']]
    result = result[cols]

    # 결측 처리
    result = result.fillna(0)

    return result

mActivity2 = process_mActivity_by_timezones(mActivity)

# check
print(f'# mActivity2 shape: {mActivity2.shape}')
mActivity2.head(1)









"""### ✅ mAmbience 추정주변소리
- Ambient sound identification labels and their respective probabilities.
- 무슨 소리가 난게 중요할까?
- 새벽에 무슨 소리던지 소리가 난게 중요한 걸까?
- 여러 가지 소리 중에 노이즈도 포함되어 있을까?
"""

def extract_labels_and_probs(row):
    items = row['m_ambience']
    labels = [item[0] for item in items]
    probs = [item[1] for item in items]
    return pd.Series({'labels': labels, 'prob': probs})

mAmbience[['labels', 'prob']]  = mAmbience.apply(extract_labels_and_probs, axis=1)
mAmbience['lifelog_date'] = mAmbience['timestamp'].astype(str).str[:10]
mAmbience = mAmbience.drop(columns=['m_ambience'])
mAmbience.head(1)

def process_mAmbience(df, top_n=3, special_labels=None):
    df = df.copy()

    # 시간 파생변수
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['hour'] = df['timestamp'].dt.hour
    df['weekday'] = df['timestamp'].dt.weekday
    df['is_weekend'] = df['weekday'] >= 5

    def map_time_period(row):
        if 0 <= row['hour'] < 7:
            return 'sleeptime'
        elif 7 <= row['hour'] < 18:
            return 'worktime'
        else:
            return 'afterwork'

    df['time_period'] = df.apply(map_time_period, axis=1)

    # 타임스탬프 차이(초단위)
    df = df.sort_values(['subject_id', 'timestamp'])
    df['duration_sec'] = df.groupby(['subject_id'])['timestamp'].diff().dt.total_seconds()
    df['duration_sec'] = df['duration_sec'].fillna(0)

    def process_group(group):
        result = {}

        time_period = group['time_period'].iloc[0]  # 그룹별 time_period 가져오기

        labels = group['labels'].tolist()
        probs = group['prob'].tolist()
        durations = group['duration_sec'].tolist()

        flat_labels = [label for labels_list in labels for label in labels_list]
        flat_probs = [float(prob) for probs_list in probs for prob in probs_list]
        repeated_durations = [dur for labels_list, dur in zip(labels, durations) for _ in labels_list]

        if not flat_labels or not flat_probs:
            return pd.Series()

        flat_probs = np.array(flat_probs)

        # prefix 설정
        prefix = f'{time_period}_'

        result[prefix + 'max_label'] = flat_labels[np.argmax(flat_probs)]
        result[prefix + 'max_prob'] = np.max(flat_probs)
        result[prefix + 'entropy'] = entropy(flat_probs, base=2)
        result[prefix + 'label_count'] = len(flat_labels)

        # 정규식
        vehicle_pattern = re.compile(r'car|vehicle|truck|bus|motorcycle|bicycle|boat|ship|train|subway|aircraft|helicopter|engine', re.IGNORECASE)
        environment_pattern = re.compile(r'outside|inside|environment|ocean|rain|waterfall|wind|fire|waves|rustling|earthquake|explosion|thunder|smoke', re.IGNORECASE)
        human_pattern = re.compile(r'speech|baby|child|laughter|crying|shout|screaming|groan|cough|hubbub|snoring|whimper|talking|singing|giggle|chatter|babbling', re.IGNORECASE)
        music_pattern = re.compile(r'music|song|singing|choir|instrument|guitar|piano|violin|vocal|jazz|hip hop|pop|rock|opera|blues|folk|electronic|dubstep|reggae|house|metal|disco|dance|flamenco|trance|techno|saxophone|synthesizer|harp|accordion|clarinet|flute|drum|tabla|tambourine|maraca|steelpan|xylophone|orchestra|band', re.IGNORECASE)

        # 분류
        vehicle_related = [(label, dur) for label, dur in zip(flat_labels, repeated_durations) if vehicle_pattern.search(label)]
        environment_related = [(label, dur) for label, dur in zip(flat_labels, repeated_durations) if environment_pattern.search(label)]
        human_related = [(label, dur) for label, dur in zip(flat_labels, repeated_durations) if human_pattern.search(label)]
        music_related = [(label, dur) for label, dur in zip(flat_labels, repeated_durations) if music_pattern.search(label)]

        # has (존재 여부)
        result[prefix + 'has_vehicle_related'] = int(len(vehicle_related) > 0)
        result[prefix + 'has_environment_related'] = int(len(environment_related) > 0)
        result[prefix + 'has_human_related'] = int(len(human_related) > 0)
        result[prefix + 'has_music_related'] = int(len(music_related) > 0)

        # sum (개수)
        result[prefix + 'sum_vehicle_related'] = len(vehicle_related)
        result[prefix + 'sum_environment_related'] = len(environment_related)
        result[prefix + 'sum_human_related'] = len(human_related)

        return pd.Series(result)

    features = df.groupby(['subject_id', 'lifelog_date', 'time_period']).apply(process_group).reset_index()
    features = features.pivot(index=['subject_id', 'lifelog_date'], columns='level_3', values=0).reset_index()

    return features

mAmbience2 = process_mAmbience(mAmbience)

# check
print(f'# mAmbience2 shape: {mAmbience2.shape}')
mAmbience2.head(1)









"""### ✅ mBle 블루투스
- Bluetooth devices around individual subject.
 - 7936 : Wearable, Headset, AV Device
 - 1796 : Peripheral (입력장치) 계열
 - 0 : 정보 없음 또는 알 수 없음(Unknown)
 - 1084 : Audio/Video (스피커, 헤드셋, 이어폰, TV 등)
 - 524 : Phone (휴대폰, 스마트폰)
 - 1060 : Headphones
 - 284 : commputer (PC, 노트북, PDA)
"""

def extract_mble_info(row):
    m_data = row['m_ble']
    address = [item['address'] for item in m_data]
    device_class = [item['device_class'] for item in m_data]
    rssi = [item['rssi'] for item in m_data]
    return pd.Series({'address': address, 'device_class': device_class, 'rssi': rssi})

mBle[['address','device_class','rssi']] = mBle.apply(extract_mble_info, axis=1)
mBle['lifelog_date'] = mBle['timestamp'].astype(str).str[:10]
mBle.head(1)

def process_mBle(df):
    df = df.copy()
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['lifelog_date'] = df['timestamp'].dt.date
    df['hour'] = df['timestamp'].dt.hour

    # 시간대 분류
    def map_time_period(row):
        if 0 <= row['hour'] < 7:
            return 'sleeptime'
        elif 7 <= row['hour'] < 18:
            return 'worktime'
        else:
            return 'afterwork'

    df['time_period'] = df.apply(map_time_period, axis=1)

    features = []

    for idx, row in df.iterrows():
        entry = ast.literal_eval(row['m_ble']) if isinstance(row['m_ble'], str) else row['m_ble']

        rssi_list = []
        class_0_cnt = 0
        class_other_cnt = 0

        for device in entry:
            try:
                rssi = int(device['rssi'])
                rssi_list.append(rssi)

                device_class = str(device['device_class'])
                if device_class == '0':
                    class_0_cnt += 1
                else:
                    class_other_cnt += 1
            except:
                continue  # malformed record

        feature = {
            'subject_id': row['subject_id'],
            'lifelog_date': row['lifelog_date'],
            'time_period': row['time_period'],
            'device_class_0_cnt': class_0_cnt,
            'device_class_others_cnt': class_other_cnt,
            'device_count': len(rssi_list),
            'rssi_mean': np.mean(rssi_list) if rssi_list else np.nan,
            'rssi_min': np.min(rssi_list) if rssi_list else np.nan,
            'rssi_max': np.max(rssi_list) if rssi_list else np.nan,
        }
        features.append(feature)

    return pd.DataFrame(features)

def summarize_mBle_daily(df):

    # row 단위 BLE feature 추출
    df = process_mBle(df)

    # 하루 + 시간대별로 groupby
    grouped = df.groupby(['subject_id', 'lifelog_date', 'time_period']).agg({
        'device_class_0_cnt': 'sum',
        'device_class_others_cnt': 'sum',
        'rssi_mean': 'mean',
        'rssi_min': 'min',
        'rssi_max': 'max',
    }).reset_index()

    # 총합 구해서 비율 계산
    total_cnt = grouped['device_class_0_cnt'] + grouped['device_class_others_cnt']
    grouped['device_class_0_ratio'] = grouped['device_class_0_cnt'] / total_cnt.replace(0, np.nan)
    grouped['device_class_others_ratio'] = grouped['device_class_others_cnt'] / total_cnt.replace(0, np.nan)

    # 필요 없는 cnt 컬럼 제거
    grouped.drop(columns=[
        'device_class_0_cnt',
        'device_class_others_cnt'
    ], inplace=True)

    # pivot해서 time_period별로 펼치기
    final = grouped.pivot(index=['subject_id', 'lifelog_date'], columns='time_period')
    final.columns = ['_'.join(col).strip() for col in final.columns.values]
    final = final.reset_index()

    return final

mBle2 = summarize_mBle_daily(mBle)

# check
print(f'\n # mBle2 shape: {mBle2.shape}')
mBle2.head(1)









"""### ✅ mGps, GPS 기반 핸드폰 위치
- Multiple GPS coordinates measured within a single minute using the smartphone.
- speed가 1보다 큰경우 정지 상태가 아니고 움직이고 있다고 판단
 - 0.5-2 : 걸어서 이동하는 경우  
 - 2-5 : 조깅
 - 5 이상 : 차를 타고 이동하는 경우

- speed가 0.5-2사이를 하루에 몇분동안 지속했는지?
- speed가 2-5사이를 하루에 몇분동안 지속했는지? (유산소 운동 시간)
- speed가 5이상을 하루에 몇분동안 지속했는지?  
"""

def extract_gps_info(row):
    m_data = row['m_gps']
    altitude = [item['altitude'] for item in m_data]
    latitude = [item['latitude'] for item in m_data]
    longitude = [item['longitude'] for item in m_data]
    speed = [item['speed'] for item in m_data]
    return pd.Series({'altitude': altitude, 'latitude': latitude, 'longitude': longitude, 'speed': speed})

mGps[['altitude','latitude','longitude','speed']] = mGps.apply(extract_gps_info, axis=1)
mGps['lifelog_date'] = mGps['timestamp'].astype(str).str[:10]
mGps = mGps.drop(columns=['m_gps'])
mGps.head(1)

# 거리 계산 함수
def haversine(coord1, coord2, unit='m'):
    lat1, lon1 = coord1
    lat2, lon2 = coord2
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a))
    r = 6371000  # 지구 반지름(m)
    return c * r if unit == 'm' else c * r / 1000

def process_mGps(df):
    df = df.copy()

    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['lifelog_date'] = df['timestamp'].dt.date
    df['week'] = df['timestamp'].dt.isocalendar().week

    expanded_rows = []

    for idx, row in tqdm(df.iterrows(), total=len(df), desc="Processing GPS data"):
        speeds = ast.literal_eval(row['speed']) if isinstance(row['speed'], str) else row['speed']
        lats = ast.literal_eval(row['latitude']) if isinstance(row['latitude'], str) else row['latitude']
        lons = ast.literal_eval(row['longitude']) if isinstance(row['longitude'], str) else row['longitude']
        alts = ast.literal_eval(row['altitude']) if isinstance(row['altitude'], str) else row['altitude']
        n = len(speeds)
        if n > 0:
            expanded_rows.append(pd.DataFrame({
                'subject_id': [row['subject_id']] * n,
                'lifelog_date': [row['lifelog_date']] * n,
                'timestamp': pd.date_range(start=row['timestamp'], periods=n, freq='1S'),
                'speed': speeds,
                'latitude': lats,
                'longitude': lons,
                'altitude': alts
            }))

    expanded_df = pd.concat(expanded_rows, ignore_index=True)

    # 벡터화
    speeds = expanded_df['speed'].values

    walk_mask = (0.5 <= speeds) & (speeds < 2)
    jog_mask = (2 <= speeds) & (speeds < 5)
    vehicle_mask = (speeds >= 5)
    le5_mask = (speeds <= 5)

    expanded_df['walk'] = walk_mask.astype(int)
    expanded_df['jog'] = jog_mask.astype(int)
    expanded_df['vehicle'] = vehicle_mask.astype(int)
    expanded_df['le5_speed'] = expanded_df['speed'].where(le5_mask)

    # 아침/저녁 구간 조건
    expanded_df['hour'] = expanded_df['timestamp'].dt.hour
    morning_condition = (expanded_df['hour'] >= 6) & (expanded_df['hour'] < 9) & (expanded_df['speed'] >= 1)
    evening_condition = (expanded_df['hour'] >= 21) & (expanded_df['hour'] <= 23) & (expanded_df['speed'] <= 1)

    # 이동 특성 계산
    movement_features = []
    for (subject_id, lifelog_date), group in expanded_df.groupby(['subject_id', 'lifelog_date']):
        all_speeds = group['speed'].values
        all_alts = group['altitude'].values
        all_lats = group['latitude'].values
        all_lons = group['longitude'].values

        active_mins = group.shape[0] / 60  # 1초 단위 → 분
        movement_ratio = (all_speeds > 1.0).mean() if len(all_speeds) > 0 else 0
        alt_change = all_alts[-1] - all_alts[0] if len(all_alts) > 0 else 0
        lat_change = all_lats[-1] - all_lats[0] if len(all_lats) > 0 else 0
        lon_change = all_lons[-1] - all_lons[0] if len(all_lons) > 0 else 0

        total_dist = 0.0
        if len(all_lats) > 1:
            for i in range(len(all_lats)-1):
                coord1 = (all_lats[i], all_lons[i])
                coord2 = (all_lats[i+1], all_lons[i+1])
                total_dist += haversine(coord1, coord2, unit='m')

        movement_features.append({
            'subject_id': subject_id,
            'lifelog_date': lifelog_date,
            'active_minutes': active_mins,
            'movement_ratio': movement_ratio,
            'alt_change': alt_change,
            'lat_change': lat_change,
            'lon_change': lon_change,
            'total_distance_m': total_dist
        })

    movement_df = pd.DataFrame(movement_features)

    # Groupby + Aggregation
    agg_funcs = {
        'walk_minutes': ('walk', lambda x: x.sum() / 60),
        'jog_minutes': ('jog', lambda x: x.sum() / 60),
        'vehicle_minutes': ('vehicle', lambda x: x.sum() / 60),
        'speed_le5_max': ('le5_speed', 'max'),
        'speed_le5_mean': ('le5_speed', 'mean'),
        'speed_le5_std': ('le5_speed', 'std')
    }

    grouped = expanded_df.groupby(['subject_id', 'lifelog_date']).agg(**agg_funcs).reset_index()
    grouped['exercise_flag'] = np.where(grouped['jog_minutes'] >= 5,1,0)

    # 아침 wakeup time
    morning_first_movement = (
        expanded_df[morning_condition]
        .groupby(['subject_id', 'lifelog_date'])['timestamp']
        .min()
        .reset_index()
        .rename(columns={'timestamp': 'morning_wakeup_time'})
    )


    # 최종 merge
    final = pd.merge(grouped, movement_df, on=['subject_id', 'lifelog_date'], how='left')
    final = pd.merge(final, morning_first_movement, on=['subject_id', 'lifelog_date'], how='left')

    # 아침 wakeup_time 처리
    valid_wakeup = final['morning_wakeup_time'].dropna()
    if not valid_wakeup.empty:
        total_seconds = valid_wakeup.dt.hour * 3600 + valid_wakeup.dt.minute * 60 + valid_wakeup.dt.second
        mean_seconds = total_seconds.mean()
        mean_hour = int(mean_seconds // 3600)
        mean_minute = int((mean_seconds % 3600) // 60)
        mean_second = int(mean_seconds % 60)
        mean_wakeup_time = time(mean_hour, mean_minute, mean_second)
    else:
        mean_wakeup_time = time(7, 0, 0)

    final['morning_wakeup_time'] = final['morning_wakeup_time'].fillna(
        pd.Timestamp.combine(pd.to_datetime('today').date(), mean_wakeup_time)
    )
    final['morning_wakeup_time'] = final['morning_wakeup_time'].dt.hour * 100 + final['morning_wakeup_time'].dt.minute

    mean_wakeup_hhmm = mean_wakeup_time.hour * 100 + mean_wakeup_time.minute

    # wake_up_early_minutes
    def compute_minutes_diff(actual_hhmm, mean_hhmm):
        actual_hour = actual_hhmm // 100
        actual_minute = actual_hhmm % 100
        mean_hour = mean_hhmm // 100
        mean_minute = mean_hhmm % 100
        actual_sec = actual_hour * 3600 + actual_minute * 60
        mean_sec = mean_hour * 3600 + mean_minute * 60
        return (mean_sec - actual_sec) / 60

    final['wake_up_early_minutes'] = final['morning_wakeup_time'].apply(lambda x: compute_minutes_diff(x, mean_wakeup_hhmm))

    return final

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# mGps2 = process_mGps(mGps)
# 
# # check
# print(f'\n # mGps2 shape: {mGps2.shape}')
# mGps2.head(1)









"""### 📂 mLight 주변 밝기
- Ambient light measured by the smartphone.
 - 어두운 밤	0.1 ~ 1 lux	캄캄한 방, 달빛 없는 밤
 - 가로등 켜진 거리	10 ~ 20 lux	흐릿한 외부 조명
 - 실내 조명	100 ~ 500 lux	사무실, 일반 거실
 - 밝은 실외	10,000 ~ 25,000 lux	맑은 날 햇빛
 - 직사광선 아래	30,000 ~ 100,000 lux	여름 한낮, 매우 강한 햇빛

- 밝기에 따라서 언제 불을 끄고 잠든 시간 추정
- 직사광선 잠에 좋은 영향을 주는지? (논문)
- 결측치 처리 x
"""

mLight['lifelog_date'] = mLight['timestamp'].astype(str).str[:10]
mLight.head(1)

def process_mLight(df):
    df = df.copy()
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['lifelog_date'] = df['timestamp'].dt.date
    df['hour'] = df['timestamp'].dt.hour
    df['is_night'] = df['hour'].apply(lambda h: h >= 22 or h < 6)

    # 하루 요약 통계
    daily_light = df.groupby(['subject_id', 'lifelog_date']).agg(
        light_mean=('m_light', 'mean'),
        light_std=('m_light', 'std'),
        light_max=('m_light', 'max'),
        light_min=('m_light', 'min'),
        light_night_mean=('m_light', lambda x: x[df.loc[x.index, 'is_night']].mean()),
        light_day_mean=('m_light', lambda x: x[~df.loc[x.index, 'is_night']].mean()),
        light_night_ratio=('is_night', 'mean')
    ).reset_index()

    results = []

    for subject_id, group in tqdm(df.groupby('subject_id'), desc="Processing light-based sleep detection"):
        group = group.sort_values('timestamp').reset_index(drop=True)

        recorded_dates = set()
        sleeping = False
        zero_count = 0
        first_zero_time = None

        for i in range(len(group)):
            light = group.loc[i, 'm_light']
            hour = group.loc[i, 'hour']

            if light == 0:
                zero_count += 1
                if zero_count == 1:
                    first_zero_time = group.loc[i, 'timestamp']
                if zero_count >= 6 and not sleeping:
                    sleep_hour = first_zero_time.hour
                    if (sleep_hour >= 21 or sleep_hour <= 2):
                        sleeping = True
            else:
                if sleeping:
                    candidate_wakeup = group.loc[i, 'timestamp']
                    wake_hour = candidate_wakeup.hour

                    if 5 <= wake_hour <= 9 and first_zero_time is not None:
                        wake_time = candidate_wakeup
                        sleep_time = first_zero_time
                        duration_min = (wake_time - sleep_time).total_seconds() / 60

                        if 0 < duration_min <= 840:
                            sleep_duration = duration_min
                        else:
                            sleep_duration = np.nan

                        lifelog_date = wake_time.date() + pd.Timedelta(days=-1)

                        if lifelog_date not in recorded_dates:
                            results.append({
                                'subject_id': subject_id,
                                'lifelog_date': lifelog_date,
                                'sleep_duration_min_mLight': sleep_duration,
                                'sleep_time_min_mLight': sleep_time.hour * 60 + sleep_time.minute,
                                'wake_time_min_mLight': wake_time.hour * 60 + wake_time.minute,
                                'hour_slept_mLight': sleep_time.hour + sleep_time.minute / 60,
                                'hour_woke_up_mLight': wake_time.hour + wake_time.minute / 60
                            })
                            recorded_dates.add(lifelog_date)

                        sleeping = False
                        zero_count = 0
                        first_zero_time = None

            if light > 0:
                zero_count = 0
                first_zero_time = None

    sleep_df = pd.DataFrame(results)

    # 정렬 + 보간
    sleep_df = sleep_df.sort_values(['subject_id', 'lifelog_date'])
    sleep_df['sleep_duration_interp_mLight'] = sleep_df.groupby('subject_id')['sleep_duration_min_mLight'].transform(lambda x: x.interpolate())

    # 시간 단위 파생 컬럼
    sleep_df['sleep_duration_hour_mLight'] = sleep_df['sleep_duration_min_mLight'] / 60
    sleep_df['sleep_duration_interp_hour_mLight'] = sleep_df['sleep_duration_interp_mLight'] / 60

    # 병합
    final = pd.merge(daily_light, sleep_df, on=['subject_id', 'lifelog_date'], how='left')

    return final

mLight2 = process_mLight(mLight)

# check
print(f'\n # mLight2 shape: {mLight2.shape}')
mLight2.head(1)

















"""### 📂 mScreenStatus 화면 사용여부

- Indicates whether the smartphone screen is in use.
 - 기상시간, 취침시간, 수면시간
 - 휴대폰 이용횟수, 이용시간
 - 00 - 05 사이에 휴대폰 이용한 건수
 - 결측치 처리 x
"""

mScreenStatus['lifelog_date'] = mScreenStatus['timestamp'].astype(str).str[:10]
mScreenStatus.head(1)

import numpy as np
import pandas as pd
from tqdm import tqdm

def process_mScreenUse(df):
    df = df.copy()
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['lifelog_date'] = df['timestamp'].dt.date
    df['hour'] = df['timestamp'].dt.hour

    # --------------------------------------
    # [1] 하루별 screen 사용 요약
    # --------------------------------------
    features = []

    for (subj, lifelog_date), group in df.groupby(['subject_id', 'lifelog_date']):
        status = group['m_screen_use'].values
        ratio_on = status.mean()
        transitions = (status[1:] != status[:-1]).sum()

        durations = []
        current = 0
        for val in status:
            if val == 1:
                current += 1
            elif current > 0:
                durations.append(current)
                current = 0
        if current > 0:
            durations.append(current)

        features.append({
            'subject_id': subj,
            'lifelog_date': lifelog_date,
            'screen_on_ratio': ratio_on,
            'screen_on_transitions': transitions,
            'screen_on_duration_avg': np.mean(durations) if durations else 0,
            'screen_on_duration_max': np.max(durations) if durations else 0,
        })

    daily_screen = pd.DataFrame(features)

    # --------------------------------------
    # [2] 수면시간 추정
    # --------------------------------------
    results = []

    for subject_id, group in tqdm(df.groupby('subject_id'), desc="Processing sleep detection"):
        group = group.sort_values('timestamp').reset_index(drop=True)

        recorded_dates = set()

        sleeping = False
        zero_count = 0
        first_zero_time = None

        for i in range(len(group)):
            screen = group.loc[i, 'm_screen_use']
            hour = group.loc[i, 'hour']

            if screen == 0:
                zero_count += 1
                if zero_count == 1:
                    first_zero_time = group.loc[i, 'timestamp']
                if zero_count >= 120 and not sleeping:
                    sleep_hour = first_zero_time.hour
                    if (sleep_hour >= 21) or (sleep_hour <= 2):
                        sleeping = True
            else:
                if sleeping:
                    candidate_wakeup = group.loc[i, 'timestamp']
                    wake_hour = candidate_wakeup.hour

                    # first_zero_time 존재 확인
                    if 5 <= wake_hour <= 9 and first_zero_time is not None:
                        wake_time = candidate_wakeup
                        sleep_time = first_zero_time
                        duration_min = (wake_time - sleep_time).total_seconds() / 60

                        if 0 < duration_min <= 840: # 14hr
                            sleep_duration = duration_min
                        else:
                            sleep_duration = np.nan

                        lifelog_date = wake_time.date() + pd.Timedelta(days=-1)

                        if lifelog_date not in recorded_dates:
                            results.append({
                                'subject_id': subject_id,
                                'lifelog_date': lifelog_date,
                                'sleep_duration_min_mScreenStatus': sleep_duration,
                                'sleep_time_min_mScreenStatus': sleep_time.hour * 60 + sleep_time.minute,
                                'wake_time_min_mScreenStatus': wake_time.hour * 60 + wake_time.minute,
                                'hour_slept_mScreenStatus': sleep_time.hour + sleep_time.minute / 60,
                                'hour_woke_up_mScreenStatus': wake_time.hour + wake_time.minute / 60
                            })
                            recorded_dates.add(lifelog_date)

                        sleeping = False
                        zero_count = 0
                        first_zero_time = None

            if screen == 1:
                zero_count = 0
                first_zero_time = None

    sleep_df = pd.DataFrame(results)

    # 정렬 + 보간
    sleep_df = sleep_df.sort_values(['subject_id', 'lifelog_date'])
    sleep_df['sleep_duration_interp_mScreenStatus'] = sleep_df.groupby('subject_id')['sleep_duration_min_mScreenStatus'].transform(lambda x: x.interpolate())

    # 시간 단위 수면시간 추가
    sleep_df['sleep_duration_hour_mScreenStatus'] = sleep_df['sleep_duration_min_mScreenStatus'] / 60
    sleep_df['sleep_duration_interp_hour_mScreenStatus'] = sleep_df['sleep_duration_interp_mScreenStatus'] / 60

    # --------------------------------------
    # [3] 최종 merge
    # --------------------------------------
    final = pd.merge(daily_screen, sleep_df, on=['subject_id', 'lifelog_date'], how='left')

    return final

mScreenStatus2 = process_mScreenUse(mScreenStatus)

# check
print(f'\n # mScreenStatus2 shape: {mScreenStatus2.shape}')
mScreenStatus2.head(1)















"""### ✅ mUsageStats 앱사용통계
- mUsageStats: Indicates which apps were used on the smartphone and for how long.

 - 몇시까지 핸드폰 보다가 잠잤는지
 - 통화, 전화 얼마나 했는지
 - YouTube 얼마나 봤는지
 - 메시지, 카카오톡 얼마나 했는지
 - NAVER 얼마나 했는지
 - 평소보다 얼마나 많은 앱을 이용했는지
 - 제외? -> 시스템 UI,One UI 홈
"""

def extract_mUsageStats_info(row):
    m_data = row['m_usage_stats']
    app_name = [item['app_name'] for item in m_data]
    total_time = [item['total_time'] for item in m_data]
    return pd.Series({'app_name': app_name, 'total_time': total_time})

mUsageStats[['app_name', 'total_time']] = mUsageStats.apply(extract_mUsageStats_info, axis=1)
mUsageStats['lifelog_date'] = mUsageStats['timestamp'].astype(str).str[:10]
mUsageStats.head(1)

def process_mUsageStats(df):
    df = df.copy()
    df['lifelog_date'] = pd.to_datetime(df['lifelog_date'])
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['요일'] = df['lifelog_date'].dt.day_name()

    # 리스트 평탄화
    exploded_df = df.explode(['app_name', 'total_time'])
    exploded_df['total_time'] = exploded_df['total_time'].astype(float)
    exploded_df['total_time'] = exploded_df['total_time'] * 0.001 / 60  # 밀리초 → 초 → 분 변환

    # app_name 특수문자 제거
    exploded_df['app_name'] = exploded_df['app_name'].astype(str).apply(
        lambda x: re.sub(r'[^가-힣a-zA-Z0-9]', '', x)
    )

    # 시스템 앱 제거
    filtered_df = exploded_df[~exploded_df['app_name'].isin(['시스템UI'])]  # '시스템UI'만 제거 (OneUI홈은 포함)

    # 주요 파생변수 생성
    def calculate_daily_metrics(group):
        last_use = group['timestamp'].max()

        app_times = {
            '통화_time': group[group['app_name'] == '통화']['total_time'].sum(),
            '전화_time': group[group['app_name'] == '전화']['total_time'].sum(),
            'YouTube_time': group[group['app_name'] == 'YouTube']['total_time'].sum(),
            '메신저_time': group[group['app_name'].isin(['메시지', '카카오톡'])]['total_time'].sum(),
            'NAVER_time': group[group['app_name'] == 'NAVER']['total_time'].sum(),
            '캐시워크_time': group[group['app_name'] == '캐시워크']['total_time'].sum(),
            '성경일독Q_time': group[group['app_name'] == '성경일독Q']['total_time'].sum(),
            'OneUI홈_time': group[group['app_name'] == 'OneUI홈']['total_time'].sum(),
        }

        return pd.Series({
            **app_times,
            'unique_app_count': group['app_name'].nunique(),
            'total_screen_time': group['total_time'].sum()
        })

    # daily metrics 생성
    daily_stats = filtered_df.groupby(['subject_id', 'lifelog_date']).apply(calculate_daily_metrics).reset_index()

    # subject_id별 평균 총화면시간 구하기
    avg_screen_time = daily_stats.groupby('subject_id')['total_screen_time'].mean().to_dict()

    # 평균대비 화면사용량(%) 생성
    def compute_screen_usage(row):
        avg_time = avg_screen_time.get(row['subject_id'], np.nan)
        if pd.isna(avg_time) or avg_time == 0:
            return np.nan
        return round((row['total_screen_time'] / avg_time - 1) * 100, 1)

    daily_stats['screen_time_vs_avg_pct'] = daily_stats.apply(compute_screen_usage, axis=1)

    return daily_stats

mUsageStats2 = process_mUsageStats(mUsageStats)

# check
print(f'\n # mUsageStats2 shape: {mUsageStats2.shape}')
mUsageStats2.head(1)









"""### ✅ mWifi 주변wifi 정보
- Wifi devices around individual subject.
 - -30 ~ -50 dBm	매우 강한 신호 (최적)
 - -51 ~ -60 dBm	강한 신호 (문제 없음)
 - -61 ~ -70 dBm	괜찮은 신호 (약간 느릴 수 있음)
 - -71 ~ -80 dBm	약한 신호 (끊김 주의)
 - -81 dBm 이하	매우 약한 신호 (거의 끊김)
"""

def extract_wifi_info(row):
    wifi_data = row['m_wifi']
    bssids = [item['bssid'] for item in wifi_data]
    rssis = [item['rssi'] for item in wifi_data]
    return pd.Series({'bssid': bssids, 'rssi': rssis})

mWifi[['bssid', 'rssi']] = mWifi.apply(extract_wifi_info, axis=1)
mWifi['lifelog_date'] = mWifi['timestamp'].astype(str).str[:10]
mWifi.head(1)

def process_mWifi(df,threshold):

    df = df.copy()
    df['timestamp'] = pd.to_datetime(df['timestamp'])

    def filter_strong_rssi(df,threshold):
        filtered_df = df.copy()
        def filter_row(row):
            bssids = row['bssid']
            rssis = row['rssi']
            # RSSI > threshold 조건 만족하는 항목만 추출
            filtered = [(b, r) for b, r in zip(bssids, rssis) if r > threshold]
            if filtered:
                new_bssids, new_rssis = zip(*filtered)
                return pd.Series({'bssid': list(new_bssids), 'rssi': list(new_rssis)})
            else:
                return pd.Series({'bssid': [], 'rssi': []})
        filtered_df[['bssid', 'rssi']] = filtered_df.apply(filter_row, axis=1)
        return filtered_df

    # === wifi 약신호 제거 ===
    df = filter_strong_rssi(df, threshold=threshold) ####

    features = []
    grouped = df.groupby(['subject_id', 'lifelog_date'])

    for (subject_id, date), group in grouped:
        scan_count = len(group)
        bssid_flat = sum(group['bssid'], [])  # flatten
        rssi_flat = sum(group['rssi'], [])    # flatten

        unique_bssid_count = len(set(bssid_flat))
        avg_rssi = sum(rssi_flat) / len(rssi_flat) if rssi_flat else None
        max_rssi = max(rssi_flat) if rssi_flat else None
        min_rssi = min(rssi_flat) if rssi_flat else None
        strong_rssi_ratio = sum(1 for r in rssi_flat if r > -60) / len(rssi_flat) if rssi_flat else 0
        empty_scan_count = sum(1 for b in group['bssid'] if len(b) == 0)

        # 가장 많이 탐지된 BSSID
        bssid_counter = Counter(bssid_flat)
        top_bssid, top_bssid_count = bssid_counter.most_common(1)[0] if bssid_counter else (None, 0)

        first_time = group['timestamp'].min()
        last_time = group['timestamp'].max()
        hour_span = (last_time - first_time).total_seconds() / 60  # 분 단위

        features.append({
            'subject_id': subject_id,
            'lifelog_date': date,
            'scan_count': scan_count,
            'unique_bssid_count': unique_bssid_count,
            'avg_rssi': avg_rssi,
            'max_rssi': max_rssi,
            # 'min_rssi': min_rssi,
            # 'strong_signal_ratio': strong_rssi_ratio,
            'empty_scan_count': empty_scan_count,
            'top_bssid': top_bssid,
            'top_bssid_count': top_bssid_count,
            'hour_span_minutes': hour_span
        })

    return pd.DataFrame(features)

mWifi2 = process_mWifi(mWifi,threshold=-60)

# check
print(f'\n # mWifi2 shape: {mWifi2.shape}')
mWifi2.head(1)









"""### ✅ wHr 심박동수
- Heart rate readings recorded by the smartwatch.

"""

wHr['lifelog_date'] = wHr['timestamp'].astype(str).str[:10]
wHr.head(1)

def get_time_block(hour):
    if 0 <= hour < 6:
        return 'early_morning'
    elif 6 <= hour < 12:
        return 'morning'
    elif 12 <= hour < 18:
        return 'afternoon'
    else:
        return 'evening'

def process_wHr_by_timeblock(df):
    df = df.copy()
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['lifelog_date'] = df['timestamp'].dt.date
    df['block'] = df['timestamp'].dt.hour.map(get_time_block)

    results = []

    for (subj, date), group in df.groupby(['subject_id', 'lifelog_date']):
        block_stats = {'subject_id': subj, 'lifelog_date': date}

        for block, block_group in group.groupby('block'):
            hr_all = []
            for row in block_group['heart_rate']:
                parsed = ast.literal_eval(row) if isinstance(row, str) else row
                hr_all.extend([int(h) for h in parsed if h is not None])

            if not hr_all:
                continue

            above_100 = [hr for hr in hr_all if hr > 100]
            block_stats[f'hr_{block}_mean'] = np.mean(hr_all)
            block_stats[f'hr_{block}_std'] = np.std(hr_all)
            block_stats[f'hr_{block}_max'] = np.max(hr_all)
            block_stats[f'hr_{block}_min'] = np.min(hr_all)
            block_stats[f'hr_{block}_above_100_ratio'] = len(above_100) / len(hr_all)

        results.append(block_stats)

    return pd.DataFrame(results)

wHr2 = process_wHr_by_timeblock(wHr)

# check
print(f'\n # wHr2 shape: {wHr2.shape}')
wHr2.head(1)







"""### ✅ wLight 앰비언트 라이트
- Ambient light measured by the smartwatch.  
  - 어두운 밤 0.1 ~ 1 lux 캄캄한 방, 달빛 없는 밤
  - 가로등 켜진 거리 10 ~ 20 lux 흐릿한 외부 조명
  - 실내 조명 100 ~ 500 lux 사무실, 일반 거실
  - 밝은 실외 10,000 ~ 25,000 lux 맑은 날 햇빛
  - 직사광선 아래 30,000 ~ 100,000 lux 여름 한낮, 매우 강한 햇빛
"""

wLight['lifelog_date'] = wLight['timestamp'].astype(str).str[:10]
wLight.head(1)

def get_time_block(hour):
    if 0 <= hour < 6:
        return 'early_morning'
    elif 6 <= hour < 12:
        return 'morning'
    elif 12 <= hour < 18:
        return 'afternoon'
    else:
        return 'evening'

def process_wLight_by_timeblock(df):
    df = df.copy()
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['lifelog_date'] = df['timestamp'].dt.date
    df['block'] = df['timestamp'].dt.hour.map(get_time_block)

    results = []

    for (subj, date), group in df.groupby(['subject_id', 'lifelog_date']):
        block_stats = {'subject_id': subj, 'lifelog_date': date}

        for block, block_group in group.groupby('block'):
            lux = block_group['w_light'].dropna().values
            if len(lux) == 0:
                continue

            block_stats[f'wlight_{block}_mean'] = np.mean(lux)
            block_stats[f'wlight_{block}_std'] = np.std(lux)
            block_stats[f'wlight_{block}_max'] = np.max(lux)
            block_stats[f'wlight_{block}_min'] = np.min(lux)

        results.append(block_stats)

    return pd.DataFrame(results)

wLight2 = process_wLight_by_timeblock(wLight)

# check
print(f'\n # wLight2 shape: {wLight2.shape}')
wLight2.head(1)









"""### ✅ wPedo 걸음수
- Step data recorded by the smartwatch.
"""

wPedo['lifelog_date'] = wPedo['timestamp'].astype(str).str[:10]
wPedo.head(1)

def process_wPedo(df):
    df = df.copy()
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['lifelog_date'] = df['timestamp'].dt.date

    summary = df.groupby(['subject_id', 'lifelog_date']).agg({
        'step': 'sum',
        'step_frequency': 'mean',
        'distance': 'sum',
        'speed': ['mean', 'max'],
        'burned_calories': 'sum'
    }).reset_index()

    # 컬럼 이름 정리
    summary.columns = ['subject_id', 'lifelog_date',
                       'step_sum', 'step_frequency_mean',
                       'distance_sum', 'speed_mean', 'speed_max',
                       'burned_calories_sum']

    return summary

wPedo2 = process_wPedo(wPedo)

# check
print(f'\n # wPedo2 shape: {wPedo2.shape}')
wPedo2.head(1)









"""### 📦 merge 데이터
- train, test 기간 서로 겹침
"""

# print('# train:',len(train))
# display(train.groupby(['subject_id'])['lifelog_date'].agg([min,max]).reset_index())
# print('# test:',len(test))
# display(test.groupby(['subject_id'])['lifelog_date'].agg([min,max]).reset_index())

mACStatus2['lifelog_date'] = mACStatus2['lifelog_date'].astype(str)
mActivity2['lifelog_date'] = mActivity2['lifelog_date'].astype(str)
mAmbience2['lifelog_date'] = mAmbience2['lifelog_date'].astype(str)
mBle2['lifelog_date'] = mBle2['lifelog_date'].astype(str)
mGps2['lifelog_date'] = mGps2['lifelog_date'].astype(str)
mLight2['lifelog_date'] = mLight2['lifelog_date'].astype(str)
mScreenStatus2['lifelog_date'] = mScreenStatus2['lifelog_date'].astype(str)
mUsageStats2['lifelog_date'] = mUsageStats2['lifelog_date'].astype(str)
mWifi2['lifelog_date'] = mWifi2['lifelog_date'].astype(str)
wHr2['lifelog_date'] = wHr2['lifelog_date'].astype(str)
wLight2['lifelog_date'] = wLight2['lifelog_date'].astype(str)
wPedo2['lifelog_date'] = wPedo2['lifelog_date'].astype(str)

df_list = [
    mACStatus2,       # 1
    mActivity2,       # 2
    mAmbience2,       # 3
    mBle2,            # 4
    mGps2,            # 5
    mLight2,          # 6
    mScreenStatus2,   # 7
    mUsageStats2,     # 8
    mWifi2,           # 9
    wHr2,             # 10
    wLight2,          # 11
    wPedo2            # 12
]

data = reduce(lambda left, right: pd.merge(left, right, on=['subject_id', 'lifelog_date'], how='outer'), df_list)
data['lifelog_date'] = data['lifelog_date'].astype(str)

# 중복체크
print(data.shape)
print(data[['subject_id','lifelog_date']].drop_duplicates().shape)

train2 = train.merge(data, on=['subject_id','lifelog_date'], how='left')

print('# train:',len(train))
display(train.groupby(['subject_id'])['lifelog_date'].agg([min,max]).reset_index())

print('# train2:',len(train2))
display(train2.groupby(['subject_id'])['lifelog_date'].agg([min,max]).reset_index())

print('# train2 shape:',train2.shape)
display(train2.head(1))

test2 = test.merge(data, on=['subject_id','lifelog_date'], how='left')

print('# test:',len(test))
display(test.groupby(['subject_id'])['lifelog_date'].agg([min,max]).reset_index())

print('# test2:',len(test2))
display(test2.groupby(['subject_id'])['lifelog_date'].agg([min,max]).reset_index())

print('# test2 shape:',test2.shape)
display(test2.head(1))

# 저장
print('# train  shape:',train.shape)
print('# train2 shape:',test2.shape)
print('# test   shape:',test.shape)
print('# test2  shape:',test2.shape)
train2.to_parquet(f"{path}/train2.parquet")
test2.to_parquet(f"{path}/test2.parquet")

"""
 'subject_id',
 'sleep_date',
 'lifelog_date',
 'Q1',
 'Q2',
 'Q3',
 'S1',
 'S2',
 'S3',

 # mACStatus 핸드폰 충전상태
 'charging_ratio',
 'charging_sum',
 'charging_transitions',
 'avg_charging_duration',
 'max_charging_duration',

 # mActivity 추정행동
 'activity_0_ratio',
 'activity_0_count',
 'activity_1_ratio',
 'activity_1_count',
 'activity_2_ratio',
 'activity_2_count',
 'activity_3_ratio',
 'activity_3_count',
 'activity_4_ratio',
 'activity_4_count',
 'activity_5_ratio',
 'activity_5_count',
 'activity_6_ratio',
 'activity_6_count',
 'activity_7_ratio',
 'activity_7_count',
 'activity_8_ratio',
 'activity_8_count',
 'dominant_activity',
 'num_unique_activities',
 'sleeptime_activity_0_ratio',
 'sleeptime_activity_0_count',
 'sleeptime_activity_1_ratio',
 'sleeptime_activity_1_count',
 'sleeptime_activity_2_ratio',
 'sleeptime_activity_2_count',
 'sleeptime_activity_3_ratio',
 'sleeptime_activity_3_count',
 'sleeptime_activity_4_ratio',
 'sleeptime_activity_4_count',
 'sleeptime_activity_5_ratio',
 'sleeptime_activity_5_count',
 'sleeptime_activity_6_ratio',
 'sleeptime_activity_6_count',
 'sleeptime_activity_7_ratio',
 'sleeptime_activity_7_count',
 'sleeptime_activity_8_ratio',
 'sleeptime_activity_8_count',
 'sleeptime_dominant_activity',
 'sleeptime_num_unique_activities',

 # mAmbience 추정주변소리
 'afterwork_entropy',
 'afterwork_has_environment_related',
 'afterwork_has_human_related',
 'afterwork_has_music_related',
 'afterwork_has_vehicle_related',
 'afterwork_label_count',
 'afterwork_max_label',
 'afterwork_max_prob',
 'afterwork_sum_environment_related',
 'afterwork_sum_human_related',
 'afterwork_sum_vehicle_related',
 'sleeptime_entropy',
 'sleeptime_has_environment_related',
 'sleeptime_has_human_related',
 'sleeptime_has_music_related',
 'sleeptime_has_vehicle_related',
 'sleeptime_label_count',
 'sleeptime_max_label',
 'sleeptime_max_prob',
 'sleeptime_sum_environment_related',
 'sleeptime_sum_human_related',
 'sleeptime_sum_vehicle_related',
 'worktime_entropy',
 'worktime_has_environment_related',
 'worktime_has_human_related',
 'worktime_has_music_related',
 'worktime_has_vehicle_related',
 'worktime_label_count',
 'worktime_max_label',
 'worktime_max_prob',
 'worktime_sum_environment_related',
 'worktime_sum_human_related',
 'worktime_sum_vehicle_related',

 # mBle 블루투스
 'rssi_mean_afterwork',
 'rssi_mean_sleeptime',
 'rssi_mean_worktime',
 'rssi_min_afterwork',
 'rssi_min_sleeptime',
 'rssi_min_worktime',
 'rssi_max_afterwork',
 'rssi_max_sleeptime',
 'rssi_max_worktime',
 'device_class_0_ratio_afterwork',
 'device_class_0_ratio_sleeptime',
 'device_class_0_ratio_worktime',
 'device_class_others_ratio_afterwork',
 'device_class_others_ratio_sleeptime',
 'device_class_others_ratio_worktime',

 # mGps, GPS 기반 핸드폰 위치
 'walk_minutes',
 'jog_minutes',
 'vehicle_minutes',
 'speed_le5_max',
 'speed_le5_mean',
 'speed_le5_std',
 'exercise_flag',
 'active_minutes',
 'movement_ratio',
 'alt_change',
 'lat_change',
 'lon_change',
 'total_distance_m',
 'morning_wakeup_time',
 'wake_up_early_minutes',

 # mLight 주변 밝기
 'light_mean',
 'light_std',
 'light_max',
 'light_min',
 'light_night_mean',
 'light_day_mean',
 'light_night_ratio',
 'sleep_duration_min_x',
 'sleep_time_hhmm_x',
 'wake_time_hhmm_x',

 # mScreenStatus 화면 사용여부
 'screen_on_ratio',
 'screen_on_transitions',
 'screen_on_duration_avg',
 'screen_on_duration_max',
 'sleep_duration_min_y',
 'sleep_time_hhmm_y',
 'wake_time_hhmm_y',

 # mUsageStats 앱사용통계
 '통화_time',
 '전화_time',
 'YouTube_time',
 '메신저_time',
 'NAVER_time',
 '캐시워크_time',
 '성경일독Q_time',
 'OneUI홈_time',
 'unique_app_count',
 'total_screen_time',
 'screen_time_vs_avg_pct',

 # mWifi 주변wifi 정보
 'scan_count',
 'unique_bssid_count',
 'avg_rssi',
 'max_rssi',
 'empty_scan_count',
 'top_bssid',
 'top_bssid_count',
 'hour_span_minutes',

 # wHr 심박동수
 'hr_afternoon_mean',
 'hr_afternoon_std',
 'hr_afternoon_max',
 'hr_afternoon_min',
 'hr_afternoon_above_100_ratio',
 'hr_evening_mean',
 'hr_evening_std',
 'hr_evening_max',
 'hr_evening_min',
 'hr_evening_above_100_ratio',
 'hr_early_morning_mean',
 'hr_early_morning_std',
 'hr_early_morning_max',
 'hr_early_morning_min',
 'hr_early_morning_above_100_ratio',
 'hr_morning_mean',
 'hr_morning_std',
 'hr_morning_max',
 'hr_morning_min',
 'hr_morning_above_100_ratio',

 # wLight 앰비언트 라이트
 'wlight_afternoon_mean',
 'wlight_afternoon_std',
 'wlight_afternoon_max',
 'wlight_afternoon_min',
 'wlight_evening_mean',
 'wlight_evening_std',
 'wlight_evening_max',
 'wlight_evening_min',
 'wlight_early_morning_mean',
 'wlight_early_morning_std',
 'wlight_early_morning_max',
 'wlight_early_morning_min',
 'wlight_morning_mean',
 'wlight_morning_std',
 'wlight_morning_max',
 'wlight_morning_min',

 # wPedo 걸음수
 'step_sum',
 'step_frequency_mean',
 'distance_sum',
 'speed_mean',
 'speed_max',
 'burned_calories_sum'
"""









"""### 📌 데이터 탐색"""

train = pd.read_parquet(f"{path}/train2.parquet")
test = pd.read_parquet(f"{path}/test2.parquet")

train.head(1)

test[['subject_id','lifelog_date','Q1','Q2','Q3','S1','S2','S3']].to_excel('./a2.xlsx')











"""### 📌 파생변수이미지
- 참고 : https://github.com/seongjiko/Pixleep/tree/master
"""

val_df = train[['subject_id','lifelog_date']].copy()
val_df.head(1)

mGps.head(1)

def make_timestamps_unique(df, timestamp_col='timestamp'):
    # 'timestamp' 컬럼을 기준으로 정렬
    df = df.sort_values(by=[timestamp_col])
    # 각 'timestamp'가 중복된 횟수를 세어 나노초 단위로 증가시킴
    df[timestamp_col] = df[timestamp_col] + pd.to_timedelta(df.groupby(timestamp_col).cumcount(), unit='ns')
    return df

def average_list_columns(df, list_columns, pk_cols=['subject_id', 'lifelog_date']):

    for col in list_columns:

        def safe_mean(x):
            if isinstance(x, list):
                return np.mean(x) if len(x) > 0 else np.nan
            elif isinstance(x, (int, float, np.integer, np.floating, type(None))):
                return x
            elif isinstance(x, (np.ndarray, pd.Series)):
                return np.mean(x)
            elif pd.api.types.is_scalar(x) and pd.isna(x):
                return np.nan
            else:
                return np.nan

        df[col] = df[col].apply(safe_mean)

    return df

def center_list_values(df, list_columns):
    for col in list_columns:
        def center(x):
            if isinstance(x, list) and len(x) > 0:
                mean = np.mean(x)
                return [np.round(v - mean,3) for v in x]
            return x  # NaN이나 비리스트는 그대로 유지
        df[col] = df[col].apply(center)
    return df

def merge_data_for_group(user, date):

    # 데이터 로드
    acc_group = mGps.copy()
    activity_group = mActivity.copy()
    hr_group = wHr.copy()
    wPedo_group = wPedo[['subject_id','timestamp','lifelog_date','step']].copy()

    # 위도, 경도, 스케일 전처리
    acc_group = center_list_values(acc_group,['latitude', 'longitude'])

    # 리스트 평균값으로 변환
    acc_group = average_list_columns(acc_group, ['altitude', 'latitude', 'longitude','speed'])
    hr_group = average_list_columns(hr_group, ['heart_rate'])

    # 'timestamp'를 고유하게 만듦
    acc_group = make_timestamps_unique(acc_group)
    activity_group = make_timestamps_unique(activity_group)
    hr_group = make_timestamps_unique(hr_group)
    wPedo_group = make_timestamps_unique(wPedo_group)

    # 'timestamp'를 인덱스로 설정하고 'subject_id'와 'date' 컬럼 제거
    mAcc_data = acc_group.set_index('timestamp').drop(columns=['subject_id', 'lifelog_date']).resample('S').nearest()
    activity_data = activity_group.set_index('timestamp').drop(columns=['subject_id', 'lifelog_date']).resample('S').nearest()
    e4Hr_data = hr_group.set_index('timestamp').drop(columns=['subject_id', 'lifelog_date']).resample('S').nearest()
    wPedo_data = wPedo_group.set_index('timestamp').drop(columns=['subject_id', 'lifelog_date']).resample('S').nearest()

    # 하루 86400초의 타임스탬프 생성
    start_time = datetime.strptime(date, '%Y-%m-%d')
    end_time = start_time + timedelta(days=1)
    all_timestamps = pd.date_range(start=start_time, end=end_time, freq='S', inclusive='left')
    merged_data = pd.DataFrame(index=all_timestamps)
    merged_data.index.name = 'timestamp'

    # 데이터 병합
    if not mAcc_data.empty:
        merged_data = merged_data.join(mAcc_data, how='left')
    if not e4Hr_data.empty:
        merged_data = merged_data.join(e4Hr_data, how='left')
    if not activity_data.empty:
        merged_data = merged_data.join(activity_data, how='left')
    if not wPedo_data.empty:
        merged_data = merged_data.join(wPedo_data, how='left')

    # 필요한 컬럼만 유지하고 NaN 값으로 채우기
    merged_data = merged_data.reindex(columns=['altitude', 'latitude', 'longitude', 'speed', 'heart_rate', 'm_activity', 'step'])

    # 선형 보간 적용
    merged_data = merged_data.interpolate(method='time')

    # subject_id와 date를 추가
    merged_data['subject_id'] = user
    merged_data['lifelog_date'] = date

    return merged_data

from sklearn.preprocessing import MinMaxScaler


def plot_time_series(data, user, date):
    # x축을 00:00:00부터 23:59:59까지 고정
    total_seconds = 86400
    time_range = pd.date_range(start=datetime.strptime(date, '%Y-%m-%d'), periods=total_seconds, freq='S')

    # 데이터를 시간 단위로 정렬
    data = data.reindex(time_range)

    # 시계열 이미지 생성
    fig, axes = plt.subplots(7, 1, figsize=(10, 10), sharex=True, facecolor='black')
    fig.patch.set_facecolor('black')

    for ax in axes:
        ax.set_facecolor('black')
        ax.spines['top'].set_visible(False)           # Hide the top spine
        ax.spines['right'].set_visible(False)         # Hide the right spine
        ax.spines['left'].set_visible(False)          # Hide the left spine
        ax.spines['bottom'].set_visible(False)        # Hide the bottom spine

    # 설정한 시간 범위에 맞게 x축 설정
    for ax in axes:
        ax.set_xlim([time_range[0], time_range[-1]])

    if 'altitude' in data.columns:
        axes[0].plot(data.index, data['altitude'], color='white')
    if 'latitude' in data.columns:
        axes[1].plot(data.index, data['latitude'], color='white')
    if 'longitude' in data.columns:
        axes[2].plot(data.index, data['longitude'], color='white')
    if 'speed' in data.columns:
        axes[3].plot(data.index, data['speed'], color='white')
    if 'heart_rate' in data.columns:
        axes[4].plot(data.index, data['heart_rate'], color='white')
    if 'm_activity' in data.columns:
        axes[5].plot(data.index, data['m_activity'], color='white')
    if 'step' in data.columns:
        axes[6].plot(data.index, data['step'], color='white')

    plt.tight_layout()  # Make the layout tight
    plt.savefig(f'{path}ch7/user{user}_{date}_ch7.png')
    # plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# """
# # [ch7] 변수 목록
# 
# 1 altitude
# 2 latitude (스케일 적용)
# 3 longitude (스케일 적용)
# 4 speed
# 5 heart_rate
# 6 m_activity
# 7 step
# ---------------------------
# 8 mLight <------ 후보
# """
# 
# bar = tqdm(range(val_df.shape[0]))
# for idx in bar:
#     user, date, *rest = val_df.iloc[idx].values
#     bar.set_description(f'user: {user}, date: {date}')
#     merged_data = merge_data_for_group(user, date)
#     plot_time_series(merged_data, user, date)

# 이미지 디렉터리 경로
image_dir = f'{path}ch7'

# 이미지 파일 목록 가져오기
image_files = [f for f in os.listdir(image_dir) if f.endswith('_ch7.png')]

# 첫 번째 이미지로 기준 크기 설정
first_image_path = os.path.join(image_dir, image_files[0])
first_image = Image.open(first_image_path)
image_size = first_image.size

# 이미지 불러오기 및 배열로 변환
images = []
for file in image_files:
    image_path = os.path.join(image_dir, file)
    image = Image.open(image_path).resize(image_size)
    images.append(np.array(image))

# 평균 이미지 계산
average_image = np.mean(images, axis=0).astype(np.uint8)

# 평균 이미지 시각화
plt.imshow(average_image)
plt.axis('off')
plt.title('Average Image')
plt.show()















"""### 📌 모델 학습"""

"""
afterwork_max_label
sleeptime_max_label
worktime_max_label
"""
# drop_features = ['afterwork_max_label','sleeptime_max_label','worktime_max_label']
drop_features = []
train = train.drop(columns=['top_bssid']+drop_features)
test = test.drop(columns=['top_bssid']+drop_features)

# sleep duration

train['sleep_duration_min_max'] = train[['sleep_duration_min_mScreenStatus','sleep_duration_min_mLight']].max(axis=1)
train['sleep_duration_min_min'] = train[['sleep_duration_min_mScreenStatus','sleep_duration_min_mLight']].min(axis=1)

train['sleep_duration_hour_max'] = train[['sleep_duration_hour_mScreenStatus','sleep_duration_hour_mLight']].max(axis=1)
train['sleep_duration_hour_min'] = train[['sleep_duration_hour_mScreenStatus','sleep_duration_hour_mLight']].min(axis=1)

train['sleep_duration_min_interp_max'] = train[['sleep_duration_interp_mScreenStatus','sleep_duration_interp_mLight']].max(axis=1)
train['sleep_duration_min_interp_min'] = train[['sleep_duration_interp_mScreenStatus','sleep_duration_interp_mLight']].min(axis=1)

train['sleep_time_min_max'] = train[['sleep_time_min_mScreenStatus','sleep_time_min_mLight']].max(axis=1)
train['sleep_time_min_min'] = train[['sleep_time_min_mScreenStatus','sleep_time_min_mLight']].min(axis=1)

test['sleep_duration_min_max'] = test[['sleep_duration_min_mScreenStatus','sleep_duration_min_mLight']].max(axis=1)
test['sleep_duration_min_min'] = test[['sleep_duration_min_mScreenStatus','sleep_duration_min_mLight']].min(axis=1)

test['sleep_duration_hour_max'] = test[['sleep_duration_hour_mScreenStatus','sleep_duration_hour_mLight']].max(axis=1)
test['sleep_duration_hour_min'] = test[['sleep_duration_hour_mScreenStatus','sleep_duration_hour_mLight']].min(axis=1)

test['sleep_duration_min_interp_max'] = test[['sleep_duration_interp_mScreenStatus','sleep_duration_interp_mLight']].max(axis=1)
test['sleep_duration_min_interp_min'] = test[['sleep_duration_interp_mScreenStatus','sleep_duration_interp_mLight']].min(axis=1)

test['sleep_time_min_max'] = test[['sleep_time_min_mScreenStatus','sleep_time_min_mLight']].max(axis=1)
test['sleep_time_min_min'] = test[['sleep_time_min_mScreenStatus','sleep_time_min_mLight']].min(axis=1)

# 요일 컬럼 추가 (예: 월요일, 화요일, ...)
train['lifelog_date'] = pd.to_datetime(train['lifelog_date'])
test['lifelog_date'] = pd.to_datetime(test['lifelog_date'])

# 요일
weekday_map = {
    0: '월요일', 1: '화요일', 2: '수요일', 3: '목요일',
    4: '금요일', 5: '토요일', 6: '일요일'
}
train['weekday'] = train['lifelog_date'].dt.dayofweek.map(weekday_map)
test['weekday'] = test['lifelog_date'].dt.dayofweek.map(weekday_map)

# 월
train['month'] = train['lifelog_date'].dt.month
test['month'] = test['lifelog_date'].dt.month

# weekend
train['weekend'] = np.where(train['weekday'].isin(['토요일','일요일']),1,0)
test['weekend'] = np.where(test['weekday'].isin(['토요일','일요일']),1,0)

def run_basemodel(train, test, common_params, random_state=42, early_stop=False):

    from sklearn.model_selection import train_test_split
    from sklearn.metrics import f1_score
    from sklearn.preprocessing import LabelEncoder
    from lightgbm import LGBMClassifier, log_evaluation, early_stopping
    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt

    train_df = train.copy()
    test_df = test.copy()

    submission_final = test_df[['subject_id', 'sleep_date', 'lifelog_date']].copy()
    submission_final['lifelog_date'] = pd.to_datetime(submission_final['lifelog_date']).dt.date

    # 타겟
    targets_binary = ['Q1', 'Q2', 'Q3', 'S2', 'S3']
    targets_binary_name = ['기상직후수면질','취침전신체적피로','취침전스트레스','수면효율','수면잠들기시간']
    target_multiclass = 'S1'
    all_targets = targets_binary + [target_multiclass]

    # 노이즈 수준 설정
    def add_noise(series, noise_level, seed=3):
        rng = np.random.default_rng(seed)
        return series * (1 + noise_level * rng.standard_normal(len(series)))

    noise_level = 0.015  # 필요에 따라 조정

    # 타겟인코딩
    # m = 0: 스무딩 없이 범주별 평균만 사용합니다. 관측 수가 많은 범주에는 적합하지만, 적은 경우 과적합 위험이 있습니다.
    # m = 1~10: 일반적인 기본값으로, 대부분의 상황에서 안정적인 성능을 보입니다.
    # m = 50~300: 관측 수가 매우 적은 범주가 많거나 데이터가 희소한 경우에 유용합니다.
    for tgt in all_targets:

      encoder_feats = ['subject_id','month','weekend']

      #### 타겟인코딩1

      subject_mean = train_df.groupby(encoder_feats)[tgt].mean().rename(f'{tgt}_te')
      train_df = train_df.merge(subject_mean, on=encoder_feats, how='left')
      test_df = test_df.merge(subject_mean, on=encoder_feats, how='left')
      global_mean = train_df[tgt].mean()
      test_df[f'{tgt}_te'] = test_df[f'{tgt}_te'].fillna(global_mean)

      # 노이즈 추가
      train_df[f'{tgt}_te'] = add_noise(train_df[f'{tgt}_te'], noise_level)
      test_df[f'{tgt}_te'] = add_noise(test_df[f'{tgt}_te'], noise_level)

      #### 타겟인코딩2

      # 새로운 범주형 열 생성
      train_df['TMP'] = train_df[encoder_feats].applymap(str).apply(lambda x: ''.join(x) ,axis=1)
      test_df['TMP'] = test_df[encoder_feats].applymap(str).apply(lambda x: ''.join(x) ,axis=1)

      # 인코더
      encoder = TargetEncoder(cols=['TMP'], smoothing=300) # 40
      encoder.fit(train_df[['TMP']], train_df[tgt])

      # 인코딩 결과를 새로운 열에 저장
      train_df[f'{tgt}_te2'] = encoder.transform(train_df[['TMP']])
      test_df[f'{tgt}_te2'] = encoder.transform(test_df[['TMP']])

      # 노이즈 추가
      train_df[f'{tgt}_te2'] = add_noise(train_df[f'{tgt}_te2'], noise_level)
      test_df[f'{tgt}_te2'] = add_noise(test_df[f'{tgt}_te2'], noise_level)

      # 불필요한 변수 제거
      train_df = train_df.drop(columns=['TMP'])
      test_df = test_df.drop(columns=['TMP'])


    # 인코딩
    PK = ['sleep_date', 'lifelog_date', 'subject_id']
    encoder = LabelEncoder()
    categorical_features = [i for i in train_df.select_dtypes(include=['object', 'category']).columns if i not in PK]
    for col in categorical_features:
        train_df[col] = encoder.fit_transform(train_df[col])
        test_df[col] = encoder.fit_transform(test_df[col])


    # X
    X = train_df.drop(columns=PK + all_targets)
    test_X = test_df.drop(columns=PK + all_targets)
    print(f'# X shape: {X.shape}')
    print(f'# test_X shape: {test_X.shape}')

    print('\n STEP1: 실험 결과 확인')
    print("=============== Validation Results ==============")
    total_avg_f1s = []
    best_iteration_temp = {k: [] for k in all_targets}
    f1_by_testsize = {}

    test_size_opt = [0.5, 0.4, 0.3, 0.2]
    for test_size in test_size_opt:
        val_f1 = []
        for col in targets_binary:

            # binary
            y = train_df[col]
            X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=test_size, random_state=random_state, stratify=y)
            best_param = best_param_dict[col].copy()
            best_param['random_state'] = random_state
            model = LGBMClassifier(**best_param)

            if early_stop:
                model.fit(
                    X_train, y_train,
                    eval_set=[(X_train, y_train), (X_valid, y_valid)],
                    callbacks=[early_stopping(stopping_rounds=100,verbose=False)]
                )
                best_iteration_temp[col].append(model.best_iteration_)
            else:
                model.fit(X_train, y_train)
                best_iteration_temp[col].append(1000)

            pred_valid = model.predict(X_valid)
            f1 = f1_score(y_valid, pred_valid)
            val_f1.append(f1)

        # multi
        y = train_df[target_multiclass]
        X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=test_size, random_state=random_state, stratify=y)
        best_param = best_param_dict['S1'].copy()
        best_param['random_state'] = random_state
        model = LGBMClassifier(**best_param, objective='multiclass', num_class=3)

        if early_stop:
            model.fit(
                X_train, y_train,
                eval_set=[(X_train, y_train), (X_valid, y_valid)],
                callbacks=[early_stopping(stopping_rounds=100,verbose=False)]
            )
            best_iteration_temp[target_multiclass].append(model.best_iteration_)
        else:
            model.fit(X_train, y_train)
            best_iteration_temp[target_multiclass].append(1000)

        pred_valid = model.predict(X_valid)
        f1 = f1_score(y_valid, pred_valid, average='macro')
        val_f1.append(f1)

        f1_by_testsize[str(test_size)] = val_f1
        avg_f1 = np.mean(val_f1)
        total_avg_f1s.append(avg_f1)
        detail = " ".join([f"{name}({tname}):{score:.4f}" for name, tname, score in zip(targets_binary + [target_multiclass], targets_binary_name + ['S1'], val_f1)])
        print(f"[test_size={test_size}] 평균 F1: {avg_f1:.4f} / [상세] {detail}")

    best_iteration_dict = {k: max(best_iteration_temp[k]) for k in all_targets}

    if early_stop==True:
      print("\n[best_iteration_dict]")
      for k, v in best_iteration_dict.items():
          print(f"{k}: {v}")

    print("\n[iteration 변화 그래프 저장]")
    for key, values in best_iteration_temp.items():
        plt.plot(test_size_opt, values, marker='o', label=key)
    plt.xlabel("test_size")
    plt.ylabel("best_iteration")
    plt.title("Best Iteration by test_size")
    plt.legend()
    plt.grid(True)
    plt.savefig("iteration_by_test_size.png")
    plt.clf()

    print(f"# 전체 평균 F1: {np.mean(total_avg_f1s):.4f}")
    print("================================================")

    # modoling with 100% train & no valid
    print('\n STEP2: 전체 데이터로 모델 재학습')
    print("====== modoling with 100% train & no valid =====")

    # binary
    binary_preds = {}
    for col in targets_binary:
        binary_params = best_param_dict[col].copy()
        binary_params['random_state'] = random_state
        y = train_df[col]

        if early_stop:
          binary_params['n_estimators']=best_iteration_dict[col]
          model = LGBMClassifier(**binary_params)
          model.fit(X, y)
        else:
          model = LGBMClassifier(**binary_params)
          model.fit(X, y)

        binary_preds[col] = model.predict(test_X)
        fi_df = pd.DataFrame({'feature': X.columns, 'importance': model.feature_importances_})
        top10 = fi_df.sort_values(by='importance', ascending=False).head(10)
        feat_str = ", ".join([f"{row['feature']}({int(row['importance'])})" for _, row in top10.iterrows()])
        print(f"[{col}] {feat_str}")

    # multiclass
    y = train_df['S1']
    binary_params = best_param_dict['S1'].copy()
    binary_params['random_state'] = random_state

    if early_stop:
      binary_params['n_estimators']=best_iteration_dict['S1']
      model = LGBMClassifier(**binary_params)
      model.fit(X, y)
    else:
      model = LGBMClassifier(**binary_params)
      model.fit(X, y)

    multiclass_pred = model.predict(test_X)
    fi_df = pd.DataFrame({'feature': X.columns, 'importance': model.feature_importances_})
    top10 = fi_df.sort_values(by='importance', ascending=False).head(10)
    feat_str = ", ".join([f"{row['feature']}({int(row['importance'])})" for _, row in top10.iterrows()])
    print(f"[S1] {feat_str}")

    # 예측 저장
    submission_final['S1'] = multiclass_pred
    for col in targets_binary:
        submission_final[col] = binary_preds[col]
    submission_final = submission_final[['subject_id', 'sleep_date', 'lifelog_date', 'Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']]
    fname = f"submission_{np.mean(total_avg_f1s)}.csv"
    submission_final.to_csv(fname, index=False)
    print(f"# {fname} 저장 완료")
    print(f"# submission shape:{submission_final.shape}")
    print("================================================")

    # 모델별 예측결과 비율 비교
    a11 = train_df[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].sum()
    a13 = train_df[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].apply(len)
    a12 = train_df[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].mean()
    a21 = submission_final[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].sum()
    a23 = submission_final[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].apply(len)
    a22 = submission_final[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].mean()
    result = pd.concat([a11, a13, a12, a21, a23, a22], axis=1)
    result.columns = ['학습sum','학습len','학습mean','테스트sum','테스트len','테스트mean']
    print('\n STEP3: 예측결과 비교표')
    display(result)

"""
[1]

# X shape: (450, 210)
# test_X shape: (250, 210)

 STEP1: 실험 결과 확인
=============== Validation Results ==============
[test_size=0.5] 평균 F1: 0.6536 / [상세] Q1(기상직후수면질):0.5714 Q2(취침전신체적피로):0.6549 Q3(취침전스트레스):0.7267 S2(수면효율):0.7953 S3(수면잠들기시간):0.8012 S1(S1):0.3718
[test_size=0.4] 평균 F1: 0.6614 / [상세] Q1(기상직후수면질):0.5629 Q2(취침전신체적피로):0.6781 Q3(취침전스트레스):0.7149 S2(수면효율):0.8015 S3(수면잠들기시간):0.7955 S1(S1):0.4155
[test_size=0.3] 평균 F1: 0.6605 / [상세] Q1(기상직후수면질):0.5581 Q2(취침전신체적피로):0.6667 Q3(취침전스트레스):0.7363 S2(수면효율):0.7817 S3(수면잠들기시간):0.7822 S1(S1):0.4377
[test_size=0.2] 평균 F1: 0.6709 / [상세] Q1(기상직후수면질):0.5952 Q2(취침전신체적피로):0.6226 Q3(취침전스트레스):0.7344 S2(수면효율):0.7692 S3(수면잠들기시간):0.8235 S1(S1):0.4807

[best_iteration_dict]
Q1: 496
Q2: 408
Q3: 344
S2: 857
S3: 641
S1: 919

[iteration 변화 그래프 저장]
# 전체 평균 F1: 0.6616
================================================

 STEP2: 전체 데이터로 모델 재학습
====== modoling with 100% train & no valid =====
[Q1] avg_rssi(352), device_class_others_ratio_worktime(343), sleep_duration_min_mScreenStatus(295), wake_time_min_mScreenStatus(274), rssi_mean_sleeptime(273), 통화_time(267), light_night_mean(267), device_class_0_ratio_worktime(253), hr_early_morning_std(246), walk_minutes(237)
[Q2] speed_le5_max(273), total_screen_time(272), charging_ratio(241), Q2_te(216), walk_minutes(214), sleeptime_entropy(208), rssi_mean_afterwork(205), hr_afternoon_mean(204), afterwork_sum_human_related(176), activity_7_ratio(174)
[Q3] device_class_0_ratio_afterwork(231), total_screen_time(207), unique_app_count(197), hr_evening_mean(196), screen_time_vs_avg_pct(191), rssi_mean_afterwork(183), OneUI홈_time(180), avg_rssi(162), wake_time_min_mScreenStatus(147), light_mean(145)
[S2] avg_rssi(540), hr_morning_min(506), wake_time_min_mScreenStatus(502), sleeptime_entropy(473), afterwork_entropy(453), sleep_duration_min_mScreenStatus(440), 전화_time(436), screen_on_ratio(396), hr_morning_mean(395), worktime_entropy(381)
[S3] max_rssi(449), wlight_evening_mean(388), device_class_0_ratio_sleeptime(366), rssi_mean_afterwork(364), wlight_early_morning_max(358), S3_te(351), rssi_min_afterwork(332), avg_rssi(329), sleep_time_min_min(299), sleeptime_entropy(277)
[S1] sleep_duration_min_mScreenStatus(1479), wake_time_min_mScreenStatus(1371), rssi_mean_afterwork(1254), worktime_entropy(1198), hr_morning_min(1174), active_minutes(1088), rssi_max_sleeptime(1077), screen_on_duration_avg(973), total_screen_time(968), speed_le5_max(944)
# submission_0.661585461523865.csv 저장 완료
# submission shape:(250, 9)
================================================

 STEP3: 예측결과 비교표
학습sum	학습len	학습mean	테스트sum	테스트len	테스트mean
Q1	223	450	0.4956	128	250	0.5120
Q2	253	450	0.5622	174	250	0.6960
Q3	270	450	0.6000	203	250	0.8120
S1	390	450	0.8667	188	250	0.7520
S2	293	450	0.6511	192	250	0.7680
S3	298	450	0.6622	198	250	0.7920
"""

# 공통 하이퍼파라미터
common_params = {
  'n_estimators': 5000,
  "learning_rate": 0.005,
  "shrinkage_rate": 0.12,
  'min_data_in_leaf':2,
  'bagging_fraction':0.9,
  'feature_fraction':0.6,
  'lambda_l1': 5,
  'lambda_l2': 1,
  'max_depth': -1,
  'n_jobs': -1,
  'verbosity': -1
}

# 모델별 세부 하이퍼파라미터
best_param_dict = {'Q1': {'learning_rate': 0.1473150575266255,
  'shrinkage_rate': 0.08585454450680065,
  'min_data_in_leaf': 13,
  'bagging_fraction': 0.5900885111562433,
  'feature_fraction': 0.7398526832500182,
  'lambda_l1': 0.7309384079752819,
  'lambda_l2': 0.010419978985191203,
  'max_depth': 2},
 'Q2': {'learning_rate': 0.1433742819325529,
  'shrinkage_rate': 0.4777741359643458,
  'min_data_in_leaf': 11,
  'bagging_fraction': 0.8942012129234453,
  'feature_fraction': 0.3442323511952453,
  'lambda_l1': 0.11108296857244106,
  'lambda_l2': 0.5000682520529595,
  'max_depth': 11},
 'Q3': {'learning_rate': 0.005440413154494791,
  'shrinkage_rate': 0.4869550654391126,
  'min_data_in_leaf': 5,
  'bagging_fraction': 0.992720410336095,
  'feature_fraction': 0.10854085794750301,
  'lambda_l1': 8.765258863766789,
  'lambda_l2': 0.010911793484805324,
  'max_depth': -1},
 'S1': {'learning_rate': 0.19808502263166988,
  'shrinkage_rate': 0.3292477285579064,
  'min_data_in_leaf': 9,
  'bagging_fraction': 0.5929013243246726,
  'feature_fraction': 0.8481981135327139,
  'lambda_l1': 0.010377995886618164,
  'lambda_l2': 0.6226891522266145,
  'max_depth': 10},
 'S2': {'learning_rate': 0.27099064035077214,
  'shrinkage_rate': 0.028901883938906636,
  'min_data_in_leaf': 9,
  'bagging_fraction': 0.8134249396247819,
  'feature_fraction': 0.2321570003912355,
  'lambda_l1': 8.780092357464005,
  'lambda_l2': 9.605716023562762,
  'max_depth': 7},
 'S3': {'learning_rate': 0.14542046442644,
  'shrinkage_rate': 0.3047247759570036,
  'min_data_in_leaf': 10,
  'bagging_fraction': 0.8493532899163512,
  'feature_fraction': 0.7940889257506005,
  'lambda_l1': 9.299803284110112,
  'lambda_l2': 0.12938944891518922,
  'max_depth': 6}
}

# 공통 하이퍼파라미터 대체 (이상한 모델의 경우)
best_param_dict['Q3'] = common_params

# 전체 평균 F1: 0.7114
best_iteration_dict = run_basemodel(train, test, best_param_dict, random_state=41, early_stop=False)















"""### 📌 모델 튜닝"""

import optuna
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from lightgbm import LGBMClassifier

def objective(trial, train_df, target_col):
    params = {
        'n_estimators': 1000,
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.5, log=True),
        'shrinkage_rate': trial.suggest_float('shrinkage_rate', 0.0, 0.5),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 1, 20),
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.5, 1.0),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.1, 1.0),
        'lambda_l1': trial.suggest_float('lambda_l1', 0.01, 10.0, log=True),
        'lambda_l2': trial.suggest_float('lambda_l2', 0.01, 10.0, log=True),
        'max_depth': trial.suggest_int('max_depth', -1, 12),
        'random_state': 42,
        'n_jobs': -1,
        'verbosity': -1
    }

    # 인코딩
    PK = ['sleep_date', 'lifelog_date', 'subject_id']
    encoder = LabelEncoder()
    categorical_features = [i for i in train_df.select_dtypes(include=['object', 'category']).columns if i not in PK]
    for col in categorical_features:
        train_df[col] = encoder.fit_transform(train_df[col])

    drop_cols = ['subject_id', 'sleep_date', 'lifelog_date', 'Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']
    X = train_df.drop(columns=drop_cols)
    y = train_df[target_col]

    X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.4, stratify=y, random_state=42)

    if target_col == 'S1':
        params['objective'] = 'multiclass'
        params['num_class'] = 3
        model = LGBMClassifier(**params)
        model.fit(X_train, y_train)
        preds = model.predict(X_valid)
        return f1_score(y_valid, preds, average='macro')
    else:
        model = LGBMClassifier(**params)
        model.fit(X_train, y_train)
        preds = model.predict(X_valid)
        return f1_score(y_valid, preds)  # 기본은 binary


# 전체 타겟에 대해 튜닝 실행
def run_optuna_all_targets(train_df, targets=['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3'], n_trials=30):
    best_params_all = {}
    for target in targets:
        print(f"\n📌 Start tuning for target: {target}")
        study = optuna.create_study(direction='maximize')
        study.optimize(lambda trial: objective(trial, train_df, target_col=target), n_trials=n_trials)
        print(f"Best F1 for {target}: {study.best_value:.4f}")
        print(f"Best Params for {target}: {study.best_params}")
        best_params_all[target] = study.best_params
    return best_params_all

"""
{'Q1': {'learning_rate': 0.1473150575266255,
  'shrinkage_rate': 0.08585454450680065,
  'min_data_in_leaf': 13,
  'bagging_fraction': 0.5900885111562433,
  'feature_fraction': 0.7398526832500182,
  'lambda_l1': 0.7309384079752819,
  'lambda_l2': 0.010419978985191203,
  'max_depth': 2},
 'Q2': {'learning_rate': 0.1433742819325529,
  'shrinkage_rate': 0.4777741359643458,
  'min_data_in_leaf': 11,
  'bagging_fraction': 0.8942012129234453,
  'feature_fraction': 0.3442323511952453,
  'lambda_l1': 0.11108296857244106,
  'lambda_l2': 0.5000682520529595,
  'max_depth': 11},
 'Q3': {'learning_rate': 0.005440413154494791,
  'shrinkage_rate': 0.4869550654391126,
  'min_data_in_leaf': 5,
  'bagging_fraction': 0.992720410336095,
  'feature_fraction': 0.10854085794750301,
  'lambda_l1': 8.765258863766789,
  'lambda_l2': 0.010911793484805324,
  'max_depth': -1},
 'S1': {'learning_rate': 0.19808502263166988,
  'shrinkage_rate': 0.3292477285579064,
  'min_data_in_leaf': 9,
  'bagging_fraction': 0.5929013243246726,
  'feature_fraction': 0.8481981135327139,
  'lambda_l1': 0.010377995886618164,
  'lambda_l2': 0.6226891522266145,
  'max_depth': 10},
 'S2': {'learning_rate': 0.27099064035077214,
  'shrinkage_rate': 0.028901883938906636,
  'min_data_in_leaf': 9,
  'bagging_fraction': 0.8134249396247819,
  'feature_fraction': 0.2321570003912355,
  'lambda_l1': 8.780092357464005,
  'lambda_l2': 9.605716023562762,
  'max_depth': 7},
 'S3': {'learning_rate': 0.14542046442644,
  'shrinkage_rate': 0.3047247759570036,
  'min_data_in_leaf': 10,
  'bagging_fraction': 0.8493532899163512,
  'feature_fraction': 0.7940889257506005,
  'lambda_l1': 9.299803284110112,
  'lambda_l2': 0.12938944891518922,
  'max_depth': 6}}
"""
best_param_dict = run_optuna_all_targets(train, n_trials=30)

best_param_dict































































